### ISSUE TITLE
Is "differentiable data augmentation" used or not for training the crafting network on CIFAR-10?

### ISSUE THREAD

**Issue by ZhengyuZhao** [lhfowl/adversarial_poisons#2]
Nice to read this interesting work! I would like to ask if the so-called "differentiable data augmentation" has also been used for training the crafting network on CIFAR-10. If I understand it correctly from the paper, such an augmentation has only been used for crafting the poisoning perturbations (with PGD). However, as can be seen from the "options.py", the ''--noaugment'' is set to 'false' by default (i.e. 'store_true'), which means the augmentation has also been used for training the crafting network.

**Comment by lhfowl** [comment]
Hi,

Thanks for the question. The "differentiable" part of the differentiable data augmentations only matters when optimizing the poisons. Otherwise, the augmentations just act a standard data augmentations. So the crafting network will be trained with these by default, but they are just treated as standard augmentations for this part.
